# Generated by Django 5.2.4 on 2025-10-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telirma', '0002_client_product_record_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_number', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telirma.client')),
            ],
        ),
        migrations.CreateModel(
            name='RapportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=255)),
                ('type_appareil', models.CharField(max_length=255)),
                ('statut_appareil', models.CharField(max_length=255)),
                ('observation', models.CharField(max_length=255)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='telirma.rapport')),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
