# Generated by Django 5.2.4 on 2025-10-03 11:57

import django.db.models.deletion
import telirma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telirma', '0003_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='titre',
            field=models.CharField(default='Rapport sans titre', max_length=200),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telirma.client'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='rapport_number',
            field=models.CharField(default=telirma.models.generate_rapport_reference, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='update_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
