# Generated by Django 5.2.4 on 2025-10-06 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telirma', '0004_rapport_titre_alter_rapport_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='date_verification',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
