# Generated by Django 5.2.4 on 2025-10-17 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telirma', '0006_rapport_verification_realiser_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField()),
                ('born_date', models.DateField(auto_now_add=True)),
                ('sexe', models.CharField(max_length=1)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
